 Load in numpy

In [2]:
import numpy as np

The Basics

In [3]:
a=np.array([1,2,3])   # 1D array
print(a)

[1 2 3]


In [4]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])   # 2D Array
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get the dimension
a.ndim


1

In [6]:
# Get Shape

a.shape  

(3,)

In [7]:
b.shape   # print 2 rows and 3 cols

(2, 3)

In [8]:
# get the type

a.dtype

dtype('int64')

In [ ]:
d=np.array([1,2,3], dtype='int16')

d.dtype

dtype('int16')

In [ ]:
#Get size
c=np.array([1,2,3], dtype='int32')  # 4 bytes

c.itemsize



4

In [14]:
# Get total size

a.nbytes

6