 Acessing/Changing specific elements, rows, coloumns, etc

In [2]:
import numpy as np

a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [3]:
a.shape

(2, 7)

In [4]:
# Get a specific element [r,c]
print(a[1,5])   # to print number 13  ----- Note index start from zero

print("Another way to access: ",a[1,-2])

13
Another way to access:  13


In [5]:
# Get a specific row

print(a[0,:])

[1 2 3 4 5 6 7]


In [6]:
# Get a specific col

print(a[:,2])

[ 3 10]


In [7]:
# Getting a little fancy [startindex:endindex:stepsize]


# suppose i want to get 2,4,6


print(a[0, 1:6:2])

[2 4 6]


In [8]:
a[1,5]=20

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [9]:
a[:,2]=5   #all 3rd col values will be 5
print(a)    

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


3D example

In [10]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Get specific elements (works outside in)
print(b[0,1,1])  # To print 4

print(b[:,1,:])


4
[[3 4]
 [7 8]]


In [13]:
# replace 

b[:,1,:]= [[9,9],[8,8]]
print(b)


[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
