Linear Algebra

In [1]:
import numpy as np

In [5]:
a=np.ones((2,3))
print(a)

print("----------------")


b=np.full((3,2),2)
print(b)

print("----------------")
print("Matrix Multiplication")

print(np.matmul(a,b))

[[1. 1. 1.]
 [1. 1. 1.]]
----------------
[[2 2]
 [2 2]
 [2 2]]
----------------
Matrix Multiplication
[[6. 6.]
 [6. 6.]]


In [9]:
# Find the determinant

c=np.identity(3)
print(c)
print("Determinant is :")
print(np.linalg.det(c))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Determinant is :
1.0


In [10]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...