Reorganizing Arrays

In [2]:
import numpy as np

In [5]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

print("curent dim: ",before.shape)


[[1 2 3 4]
 [5 6 7 8]]
curent dim:  (2, 4)


In [14]:
after = before.reshape((1,8))



print(after)

print("----------------------")

print(before.reshape((8,1)))

print("----------------------")

print(before.reshape((2,4)))

print("----------------------")

print(before.reshape((4,2)))

print("----------------------")

print(before.reshape((2,2,2)))

[[1 2 3 4 5 6 7 8]]
----------------------
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
----------------------
[[1 2 3 4]
 [5 6 7 8]]
----------------------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
----------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
print(before.reshape((2,3))) # This will not work

ValueError: cannot reshape array of size 8 into shape (2,3)

In [20]:
# Vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])


print(np.vstack([v1,v2,v1,v2]))

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [26]:
# Horizontal  stack

h1=np.ones((2,4))
h2=np.zeros((2,2))

print(h1)
print("-------------")
print(h2)
print("-------------")

print(np.hstack((h1,h2)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
-------------
[[0. 0.]
 [0. 0.]]
-------------
[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]
