 Acessing/Changing specific elements, rows, coloumns, etc

In [8]:
import numpy as np

a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [9]:
a.shape

(2, 7)

In [ ]:
# Get a specific element [r,c]
print(a[1,5])   # to print number 13  ----- Note index start from zero

print("Another way to access: ",a[1,-2])

13
Another way to access:  13


In [11]:
# Get a specific row

print(a[0,:])

[1 2 3 4 5 6 7]


In [12]:
# Get a specific col

print(a[:,2])

[ 3 10]


In [16]:
# Getting a little fancy [startindex:endindex:stepsize]


# suppose i want to get 2,4,6


print(a[0, 1:6:2])

[2 4 6]


In [17]:
a[1,5]=20

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
a[:,2]=5   #all 3rd col values will be 5
print(a)    

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
