Initializing Different Type of Array

In [2]:
import numpy as np

In [3]:
# All zeros matrix

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
# All ones matrix
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
# Any other matrix
np.full((2,2),55)

array([[55, 55],
       [55, 55]])

In [7]:
# Any other number (full like)
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [8]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.950983  , 0.15313427],
       [0.80908531, 0.78824398],
       [0.43837333, 0.74268467],
       [0.40754343, 0.53273624]])

In [10]:
# Random integer values

np.random.randint(-4,8, size=(3,4))

array([[ 6,  1,  2, -2],
       [ 2,  4, -1,  1],
       [ 2,  1, -3,  2]], dtype=int32)

In [11]:
# The identity matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
# Repeat an array

arr=np.array([[1,2,3]])
print(arr)
r1=np.repeat(arr,3,axis=0)
print("rRepeated array:\n",r1)

[[1 2 3]]
rRepeated array:
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
