Mathematics

In [3]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [6]:
print(a+2)

[3 4 5 6 7]


In [7]:
print(a-2)

[-1  0  1  2  3]


In [8]:
print(a*2)

[ 2  4  6  8 10]


In [9]:
print(a/2)

[0.5 1.  1.5 2.  2.5]


In [11]:
b = np.array([4,5,7,9,6])
print(b)


[4 5 7 9 6]


In [12]:
print(a+b)

[ 5  7 10 13 11]


In [13]:
print(a**2)

[ 1  4  9 16 25]


In [ ]:
# Take the sin


print(np.sin(a))
print(np.cos(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
